name: Go

on:
  push:
    branches: [ redis-4.x-cgo ]
  pull_request:
    branches: [ redis-4.x-cgo ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
    - uses: actions/checkout@v2
  
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.10
        
    - name: checkout jemalloc
      run: git clone https://github.com/jemalloc/jemalloc/tree/04380e79f1e2428bd0ad000bbc6e3d2dfc6b66a5
      
    - name: checkout redis
      run: git clone https://github.com/redis/redis/tree/238c9bd0863e713f018587e79f452ade845bee91 
        
    - name : init
      run: go mod init
    - name: Build
      run: go build -mod=mod -v ./...
      #run: make

    - name: Test
      run: go test -v ./...
